spring.application.name=backend

# Configuração do banco H2
spring.datasource.url=jdbc:h2:file:./database
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Inicialização do banco com scripts SQL
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:database.db
spring.sql.init.data-locations=classpath:seeds.db

# Configurações adicionais do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
