spring.application.name=backend

# Configuracao do banco H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Inicializacao do banco com scripts SQL
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Evita que o Hibernate recrie as tabelas depois da carga SQL
spring.jpa.hibernate.ddl-auto=none

# Configuracoes adicionais do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
